name: Display Name

on:
  push:
    branches:
      - master

jobs:
  display_name:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Display Name
      run: |
        echo "Pavlo"
        echo "Sych"
